apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: event-timeout
spec:
  hosts:
    - event-service
  http:
    - match:
        - uri:
            prefix: /event
          sourceLabels:
            app: ground-event-service
      route:
        - destination:
            host: event-service
            port:
              number: 8080
      timeout: 0.5s